development:
  adapter: postgresql
  database: jobs_development
  host: localhost

test:
  adapter: postgresql
  database: jobs_test
  host: localhost

production:
  adapter: postgresql
  database: jobs_production
